feat(register): new user registration
CashStory/api pull request #3
Opened 2020-10-09 14:40 UTC by gilsonbridge

updated APIs for new user registration

2020-10-13 13:17 UTC, BobCashStory requested changes

2020-10-13 13:17 UTC, BobCashStory commented on server/routes.ts
> +  router.route('/register').post(auth.register);
Why not put it in the `auth` scope ?

2020-10-13 13:17 UTC, BobCashStory commented on server/controllers/AuthCtrl.ts
> +  register = async (req, res: Response): Promise<any> => {
You should provide test with this one

2020-10-14 07:24 UTC, gilsonbridge commented on server/routes.ts
> +  router.route('/register').post(auth.register);
Updated in commit a909fc0

2020-10-14 07:25 UTC, gilsonbridge commented on server/controllers/AuthCtrl.ts
> +  register = async (req, res: Response): Promise<any> => {
Updated in commit a909fc0

2020-10-15 01:04 UTC, BobCashStory approved these changes

2020-10-15 01:04 UTC, merged